<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <ApplicationIcon>..\..\resources\icons\app.ico</ApplicationIcon>
    <Version>0.2.2</Version>
    <AssemblyVersion>0.2.2.0</AssemblyVersion>
    <FileVersion>0.2.2.0</FileVersion>
    <RootNamespace>Object1688.Logging</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Object1688.Shared\Object1688.Shared.csproj" />
  </ItemGroup>

</Project>